version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    container_name: foodgram-db
    env_file: ./.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: feodorpyth/foodgram_backend
    container_name: foodgram-backend
    env_file: ./.env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

  frontend:
    image: feodorpyth/foodgram_frontend
    container_name: foodgram-front
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    container_name: foodgram-nginx
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
